Component fixes
Doenet/DoenetTools pull request #1212
Opened 2022-05-14 06:24 UTC by ernzher

DoenetML components fixes (make inline) - updateValue, callAction, triggerSet 
Refactor general components - Checkbox, Button, IncrementMenu
uiDocs - Checkbox and some minor fixes

2022-05-15 18:37 UTC, clary149 requested changes
See doenet.org for how margins should look

Still needs IncrementMenu centered

2022-05-15 18:37 UTC, clary149 commented on src/_reactComponents/PanelHeaderComponents/Button.jsx
> -import React, { useState } from 'react';
What task are you completing in this file? Creates weird right margin for buttons used in menus.
<img width="242" alt="Screen Shot 2022-05-15 at 1 32 06 PM" src="https://user-images.githubusercontent.com/68914928/168488395-ea9e95bb-65fc-45d5-80ab-738033fb5858.png">

2022-05-15 18:37 UTC, clary149 commented on src/_reactComponents/PanelHeaderComponents/Checkbox.jsx
>  import React, { useRef } from 'react';
Also creates weird margin on right side of component.
<img width="234" alt="Screen Shot 2022-05-15 at 1 33 26 PM" src="https://user-images.githubusercontent.com/68914928/168488469-c9b6eb2e-1492-4a9d-80bd-4e9b9cc7f2f6.png">
<img width="234" alt="Screen Shot 2022-05-15 at 1 35 30 PM" src="https://user-images.githubusercontent.com/68914928/168488553-95a433d5-0867-4afe-a632-e4abba5d0d41.png">

2022-05-18 16:51 UTC, kevincharles commented
It's my understanding these changes are in other PR's.  closing

2022-05-18 16:51 UTC, closed without merging