Boolean input tag (issue fixes)
Doenet/DoenetTools pull request #1606
Opened 2022-09-12 09:26 UTC by keaganeng

Fixed the following issues:
* https://github.com/Doenet/DoenetTools/issues/1575
* https://github.com/Doenet/DoenetTools/issues/1576

2022-09-12 14:18 UTC, kevincharles commented
Please update line 92 to go back to ID's not name
  `const inputKey = name + '_input';`

2022-09-12 16:05 UTC, dqnykamp requested changes

2022-09-12 16:05 UTC, dqnykamp commented on src/Viewer/renderers/booleanInput.jsx
> +  console.log(label);
Delete or comment out this line

2022-09-12 16:05 UTC, dqnykamp commented on src/Viewer/renderers/booleanInput.jsx
> +  const inputKey = name + '_input';
Revert this change.

2022-09-13 09:02 UTC, keaganeng commented on src/Viewer/renderers/booleanInput.jsx
> +  const inputKey = name + '_input';
Done

2022-09-13 09:03 UTC, keaganeng commented on src/Viewer/renderers/booleanInput.jsx
> +  console.log(label);
Done

2022-09-13 13:36 UTC, merged